services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: url-shortener-postgres
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url-shortener-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - url-shortener-network

  # Jaeger for tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: url-shortener-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # HTTP collector
      - "14250:14250"  # gRPC collector
    networks:
      - url-shortener-network

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: url-shortener-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - url-shortener-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: url-shortener-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - url-shortener-network

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  url-shortener-network:
    driver: bridge 